### ISSUE TITLE
Phase 1: Website Body

### ISSUE THREAD

**Issue by diagnose** [brandonberney/research-and-innovation#2]
# Body

![home page](https://user-images.githubusercontent.com/7992425/94459419-513a8580-0185-11eb-8447-4332263a190f.jpg)

> This is a prototype of the homepage that includes the header, background, and footer.

The body of the page should be a black to red fade using the official colors of the University of Louisville.

## Requirements Checklist:

- [x] Body should include the title of the page currently selected

- [x] Background should be a black to red fade

![CardTech website background](https://user-images.githubusercontent.com/72048107/95758703-ce322880-0c76-11eb-99ca-36266747358e.png)

- [x] 50% black

- [x]  Blur between colors in the middle ( 15%)

- [x] 50% red

- [x] background will cover the entire page

- [x] Body should be part of an ASP.NET template, allowing other pages to insert their `<body>` content into the template.

**Comment by Erika-Maglasang** [comment]
#12 background has been created
