### ISSUE TITLE
Enhancement: Issue/PR Templates

### ISSUE THREAD

**Issue by diagnose** [brandonberney/research-and-innovation#22]
It is possible to create templates for issues and pull requests.

See the article [here.](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates)

Although we already have many issues created, it may still be helpful to create templates for these and especially pull requests.

Thoughts?

**Comment by Erika-Maglasang** [comment]
Nice article, I'll follow this for the next pull request, and I'll try to update some of the issues in phase 2 to fit this format.
