### ISSUE TITLE
Guide for how to make a Pull request

### ISSUE THREAD

**Issue by Erika-Maglasang** [brandonberney/research-and-innovation#25]
1. Create a new branch from the current master branch

 2. Make your changes to the new branch

3. After changes are made select the "Changes" option from the Team Explore

- describe the changes you made and select the files that you want to change

- After selecting files and describing changes click the drop down arrow of "Commit All" 

- Select the "Commit All and Push" option

*Changes will be applied to the current branch that you are in (Changes cannot be applied to the master branch because it is a protected branch, Changes will be denied if you click commit and push on this branch)*

4. Your branch should be visible from the GitHub ( this show that you successfully pushed your branch)

5. Access GitHub from the web browser 

6. Create a new pull request in GitHub

7. Select the master branch and the branch that you made changes to

8. Describe the changes and add pictures for reference

**Comment by diagnose** [comment]
I've moved this to the wiki since this isn't necessarily an 'issue.'

**Comment by Erika-Maglasang** [comment]
Issue has been added to the wiki. Please take a look at it because I added an additional step.
