### ISSUE TITLE
Phase 2: Drop down navigation bar

### ISSUE THREAD

**Issue by Erika-Maglasang** [brandonberney/research-and-innovation#28]
# Drop down navigation bar

![Screenshot 2020-10-20 12 00 26](https://user-images.githubusercontent.com/72048107/96612609-f3084a80-12cb-11eb-8c01-30fc07adbdba.png)
> This is a picture of the current view of the website

![image](https://user-images.githubusercontent.com/72048107/96613528-0f58b700-12cd-11eb-9ef8-738655ebb86c.png)
> This is a reference picture from google for how the drop down bar should function

**Since we have so many pages, it would be a good idea to add drop down capabilities to the navigation bar, this will help us organize all page links into categories that are applicable to the user**

## Requirements Checklist:

- [ ] Navigation bar will reveal a list of items when the user hovers over the navigation bar link

- [ ] That list will also reveal it's own subsequent list if applicable

### For Students Navigation Item

- [ ] Students Page

- [ ] Student Login (Login, Register, Who should Register)

- [ ] Student Forms (Reveal a list of student forms)

### For Researcher Navigation Item

- [ ] Researcher Page 

- [x] Researcher Spotlight ( Researcher Page list item)

- [x] Project Location (Researcher Page list item)

- [ ] Researcher Login (Login, Register, Who should Register)

- [x] Researcher Forms (List of Researcher Forms)

- [x] Apply for Research (Apply for Research Form)

### Help

- [ ] Contacts Page

- [x] How to apply for research (How to apply for research page (Promotional Page))
- [ ] How do I Sign Up? (Login, Register, Who should Register)

- [ ] Who can Sign Up (Promotion page)

- [x] FAQ

### For Industry

- [ ] Grants

- [x] Grants Forms (Grants item)

- [ ]Industry 

- [x] Industry Forms (Industry list item)

- [ ] Industry Login (Industry item (Login, Register, Who should register))

- [ ] Sponsor page

- [x] Sponsor a Researcher (sponsor list item)

- [ ] Sponsor Login (sponsor item (Login, Register, Who should register))

### For Community

- [x] New Articles ( list of recent news article)

- [ ] Events

- [x] Event Schedule (Events list item)

- [x] Attend an Event (Events list item)

- [ ] Community Login (Login Register, Who should Register)

**Comment by Erika-Maglasang** [comment]
@brandonberney can you try to work on this issue, I will also be working on it as well.

**Comment by diagnose** [comment]
I don't believe we should include a login link under each section since we already have a login link in the top right. Working on this now.
