### ISSUE TITLE
Phase 1: Website Background

### ISSUE THREAD

**Issue by Erika-Maglasang** [brandonberney/research-and-innovation#5]
![CardTech website background](https://user-images.githubusercontent.com/72048107/95681538-58628a00-0bae-11eb-984f-9cc8c1b25611.png)

- [ ] Black to red gradient

- [ ] 50% black

- [ ] Blur between colors in the middle ( 15%)

- [ ] 50% red

- [ ] background will cover the entire page

**Comment by diagnose** [comment]
This is related to issue #2. Please copy this information over to that one, thanks!
