### ISSUE TITLE
Phase 2: Help Page

### ISSUE THREAD

**Issue by Erika-Maglasang** [brandonberney/research-and-innovation#8]
![CardTech Inc Help Page ](https://user-images.githubusercontent.com/72048107/95683265-15a5af80-0bb8-11eb-998a-1218a08812d5.png)

- [ ] modules on the page will have rounded edges

- [x] the office location and address of the research and innovation center will be displayed in the top module

- [x] A click link will be contained in the image of the location and the user will be navigated to a map of the location

- [x] phone numbers will be contained on the website in the bottom left module

- [x] social media click links will be contained in the bottom right module

- [x] images can be clicked on and will lead the user to the appropriate social media page

**Comment by diagnose** [comment]
Resolved with #27. Closing.
